name: veinmind-tools
on: [push, pull_request]
jobs:
  package-veinmind-backdoor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cp -r ./veinmind-common ./veinmind-backdoor && rm -rf ./veinmind-backdoor/veinmind-common/go
          cd veinmind-backdoor
          tar -cvzf veinmind-backdoor.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-backdoor.tar.gz
          path: ./veinmind-backdoor/veinmind-backdoor.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-backdoor/veinmind-backdoor.tar.gz
  package-veinmind-sensitive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cp -r ./veinmind-common ./veinmind-sensitive && rm -rf ./veinmind-sensitive/veinmind-common/go
          cd veinmind-sensitive
          tar -cvzf veinmind-sensitive.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-sensitive.tar.gz
          path: ./veinmind-sensitive/veinmind-sensitive.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-sensitive/veinmind-sensitive.tar.gz
  package-veinmind-history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cp -r ./veinmind-common ./veinmind-history && rm -rf ./veinmind-history/veinmind-common/go
          cd veinmind-history
          tar -cvzf veinmind-history.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-history.tar.gz
          path: ./veinmind-history/veinmind-history.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-history/veinmind-history.tar.gz
  build-amd64-veinmind-malicious:
    runs-on: ubuntu-18.04
    container:
      image: veinmind/go1.16:1.0.5-stretch
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - run: cd veinmind-malicious && /bin/bash -x ../scripts/build/build_veinmind_malicious_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-malicious-amd64
          path: ./veinmind-malicious/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-malicious/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-static-veinmind-weakpass:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: "community,static"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd veinmind-weakpass && /bin/bash -x ../scripts/build/build_veinmind_weakpass_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64
          path: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-dynamic-veinmind-weakpass:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    container:
      image: veinmind/go1.16:1.0.5-stretch
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: "community,dynamic"
    steps:
      - uses: actions/checkout@v2
      - run: cd veinmind-weakpass && /bin/bash -x ../scripts/build/build_veinmind_weakpass_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64-dynamic
          path: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-veinmind-asset:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd veinmind-asset && /bin/bash -x ../scripts/build/build_veinmind_asset_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-asset-amd64
          path: ./veinmind-asset/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-asset_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-veinmind-runner:
    runs-on: ubuntu-latest
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    needs: build-amd64-static-veinmind-weakpass
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd veinmind-runner && /bin/bash -x ../scripts/build/build_veinmind_runner_amd64.sh
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-weakpass-amd64
      - run: |
          mv veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./veinmind-weakpass/veinmind-weakpass
          mv ./veinmind-runner/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-runner_${{env.CI_GOOS}}_${{env.CI_GOARCH}} veinmind-runner-entrypoint
          rm -rf ./veinmind-runner && mv veinmind-runner-entrypoint veinmind-runner
          tar cvzf veinmind-runner.tar.gz veinmind-runner veinmind-weakpass/veinmind-weakpass veinmind-sensitive veinmind-history veinmind-backdoor
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-runner.tar.gz
          path: veinmind-runner.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: veinmind-runner.tar.gz
  push-veinmind-backdoor:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-backdoor && rm -rf ./veinmind-backdoor/veinmind-common/go
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            veinmind/veinmind-backdoor:latest
            veinmind/veinmind-backdoor:${{github.ref_name}}
          context: ./veinmind-backdoor
  push-veinmind-sensitive:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-sensitive && rm -rf ./veinmind-sensitive/veinmind-common/go
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            veinmind/veinmind-sensitive:latest
            veinmind/veinmind-sensitive:${{github.ref_name}}
          context: ./veinmind-sensitive
  push-veinmind-history:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-history && rm -rf ./veinmind-history/veinmind-common/go
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
          tags: |
            veinmind/veinmind-history:latest
            veinmind/veinmind-history:${{github.ref_name}}
          context: ./veinmind-history
  push-veinmind-malicious:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-amd64-veinmind-malicious
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-malicious-amd64
      - run: mv veinmind-malicious_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./veinmind-malicious
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            veinmind/veinmind-malicious:latest
            veinmind/veinmind-malicious:${{github.ref_name}}
          context: ./veinmind-malicious
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}
  push-veinmind-weakpass:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-amd64-dynamic-veinmind-weakpass
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-weakpass && rm -rf ./veinmind-weakpass/veinmind-common/python
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-weakpass-amd64-dynamic
      - run: mv veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./veinmind-weakpass
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            veinmind/veinmind-weakpass:latest
            veinmind/veinmind-weakpass:${{github.ref_name}}
          context: ./veinmind-weakpass
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}
  push-veinmind-asset: 
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-asset && rm -rf ./veinmind-asset/veinmind-common/python
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/veinmind-asset:latest
            veinmind/veinmind-asset:${{github.ref_name}}
          context: ./veinmind-asset
  push-veinmind-runner:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    needs: [push-veinmind-backdoor, push-veinmind-sensitive, push-veinmind-history, push-veinmind-malicious, push-veinmind-weakpass, push-veinmind-asset]
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-runner && rm -rf ./veinmind-runner/veinmind-common/python
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            veinmind/veinmind-runner:latest
            veinmind/veinmind-runner:${{github.ref_name}}
          context: ./veinmind-runner
